@echo off
setlocal

REM
REM Copyright 2015 the original author or authors.
REM
REM Licensed under the Apache License, Version 2.0 (the "License");
REM you may not use this file except in compliance with the License.
REM You may obtain a copy of the License at
REM
REM      http://www.apache.org/licenses/LICENSE-2.0
REM
REM Unless required by applicable law or agreed to in writing, software
REM distributed under the License is distributed on an "AS IS" BASIS,
REM WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
REM See the License for the specific language governing permissions and
REM limitations under the License.
REM

REM This is a generic Gradle launcher for Windows.
REM It is generated by Gradle and should not be edited.

set APP_HOME=%~dp0

set APP_NAME=Gradle

set DEFAULT_JVM_OPTS=

set DEFAULT_CLASSPATH=%APP_HOME%gradle\wrapper\gradle-wrapper.jar

set CLASSPATH=%DEFAULT_CLASSPATH%

set GRADLE_OPTS=%DEFAULT_JVM_OPTS%

"%JAVA_HOME%\bin\java" %GRADLE_OPTS% -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*